version: '3.7'
services:
  frontend-app:
    build: .
    # command: sh -c "npm start"
    ports:
      - 4200:80
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
      - node_modules:/home/node/app/node_modules
volumes:
  node_modules: